### ISSUE TITLE
使用指令時發生問題

### ISSUE THREAD

**Issue by gofunz** [Mombuyish/Scaffold#2]
使用指令：
`php artisan make:scaffold Post`

出現錯誤：
` The "--all" option does not exist.`

Laravel Version：5.4.36

**Comment by Mombuyish** [comment]
Hi, @ZhangChinfu 
抱歉我沒有考慮到先前版本適應性
建議你可以先使用 1.0.2 或者我等等會進行版本修正
```
$ composer require "yish/scaffold:1.0.2"
```

**Comment by Mombuyish** [comment]
Hi, @ZhangChinfu 
已經修正好囉，請你更新至最新版本 1.0.5

**Comment by gofunz** [comment]
Hi, @Mombuyish 
更新後，發生新的問題：
`Command "make:factory" is not defined.`

**Comment by Mombuyish** [comment]
@ZhangChinfu 
可能要請你升級到 5.5 因為 make:factory 是 5.5 or later 之後才提供的
或者是我晚點會加入版本判斷跳過這個 < 5.4

TODO
5.5 or later => supported --all, make:factory
5.4 or previous => no supported.

**Comment by Mombuyish** [comment]
done
1.0.6
